export const testData = [
    {
        id: 13902,
        title: "This is News-1",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
    {
        id: 13903,
        title: "This is News-2",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
    {
        id: 13904,
        title: "This is News-3",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
    {
        id: 13905,
        title: "This is News-4",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
    {
        id: 13906,
        title: "This is News-5",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
    {
        id: 13907,
        title: "This is News-6",
        url: "https://www.google.com",
        imageUrl: "https://via.placeholder.com/750",
        summary: "summary",
        newsSite: "NASA",
        featured: false,
        publishedAt: "2022-04-06T22:09:10.000Z",
    },
]